# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='affectation',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
    ]
