# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0002_patient_affectation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='affectation',
            field=models.BooleanField(default=False),
        ),
    ]
