# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-08 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0003_auto_20170207_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='choix_1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='choix_2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='choix_3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='jour',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medecin',
            field=models.IntegerField(),
        ),
    ]
